### PR TITLE
Matching Frontend

### PR DESCRIPTION
**Pull request by larrywang0701**
#49 and #50

# Steps to try (with backend #67):
  - 1. Run both frontend and matching service backend
  - 2. Login with an account
  - 3. Click "Practice an Interview" on the page header
  - 4. Select difficulties and topics, then start matching
  - 5. Within 60 seconds, open another browser window (use incognito window, or use another browser application) and repeat steps ii-iv with a different user account
  - 6. The two users (in two browser windows) would be matched together (both automatically navigate to the "Get Ready" page)
  - 7. If you didn't do step v within 60 second after starting matching in step 4, the first browser window will show a "Matching Failed" page
  - 8. Click "I'm Ready" on both browser pages, and both pages will navigate to an empty collaboration page, and for now a successful matching have been made
  - 9. If two users both failed to get ready in time, they will both show a failed page. If one user get ready in time and the other not, the one who failed to get ready in time will show a failed page and the one already get ready will automatically retry matching.

# Screenshots
## Start Matching Page
image
## Waiting Matching Page
image
## Failed Matching Page (due to matching time exceeded)
image
## Get Ready Page
image
## Get Ready Page (waiting for the other user)
image
## Failed Matching Page (due to not getting ready in time)
image
## Waiting Matching Page (after the other user didn't get ready in time)
image

### CODE REVIEW

**Comment by brein62** [comment]
i love the matching in progress screen. good job!

**Comment by larrywang0701** [comment]
> i love the matching in progress screen. good job!
> 
> for difficulties, can see if the `DifficultyEdit` component may look nicer compared to the `Difficulty` component? if `Difficulty` looks nicer, then it's fine

`DifficultyEdit`:
image

`Difficulty`:
image

Personally I think `Difficulty` with a background is more clear compared to `DifficultyEdit`

**Comment by brein62** [comment]
> > i love the matching in progress screen. good job!
> > for difficulties, can see if the `DifficultyEdit` component may look nicer compared to the `Difficulty` component? if `Difficulty` looks nicer, then it's fine
> 
> `DifficultyEdit`: image
> 
> `Difficulty`: image
> 
> Personally I think `Difficulty` with a background is more clear compared to `DifficultyEdit`

i think let it be i can explore how to make it look nicer after this gets merged hehe

**Review by zacwong2151 — APPROVED** [review]
lgtm can merge!

**Pull request merged**
