### PR TITLE
Update logout function in AuthContext to remove from matching queue

### LINKED ISSUE #93: [Matching Service] Implement functionality for users to leave queue on logout

### PR DESCRIPTION
**Pull request by brein62**
Main functionality done. Fixes #93 

Things to discuss (before merging):
- How to handle expired tokens in user service (probably a nice to have) - refresh tokens?

### CODE REVIEW

**Comment by brein62** [comment]
it was literally a one liner fix... sorry for being useless

LOL

**Review by wjayee — APPROVED** [review]
lgtm LOL its aight but if the token's expired maybe js get the user to log in again to get a new token ?

**Comment by tiongMax** [comment]
> lgtm LOL its aight but if the token's expired maybe js get the user to log in again to get a new token ?

yeah just like canvas or other app

**Comment by brein62** [comment]
the problem with logging out instantly and telling the user to log in again is that it can disrupt user flow during the matching process. currently the implementation once token expires is we do nothing and if the user loads the app again he logs out

most apps use refresh token for this case but not sure what are yalls thoughts. i’ll check the given user service for inspiration as well Lol

**Comment by wjayee** [comment]
hmm then i think its bttr to use refresh tokens since our app doesnt require a high level of security like edurec where it kicked u out every 15 mins
so... we use access and refresh tokens ?

**Comment by brein62** [comment]
> hmm then i think its bttr to use refresh tokens since our app doesnt require a high level of security like edurec where it kicks u out every 15 mins so... we use access and refresh tokens ?

okie then sounds good will implement

**Pull request merged**
