### PR TITLE
Fix page transitioning (between matching and collab pages), where there was an awkward intermediate page

### PR DESCRIPTION
**Pull request by zacwong2151**
added `isLoading` variables

### CODE REVIEW

**Review by brein62 — APPROVED** [review]
LGTM!

transition is so fast that i had to video record and slow down the video to see the effects lol but it looks good there as well

ezgif-3-67a72669c9

**Comment by zacwong2151** [comment]
> LGTM!
> 
> transition is so fast that i had to video record and slow down the video to see the effects lol but it looks good there as well
> 
> however, i rechecked with zihan's original frontend PR and it seems like he's fixed it on his own in his original frontend PR, though both works - so these changes may not be necessary
> 
> i approved it since no functionality is affected and some of the logging changes may be helpful
> 
> ezgif-3-67a72669c9 [ ezgif-3-67a72669c9 ](https://private-user-images.githubusercontent.com/15770059/382551984-fa38a09b-ce7e-4943-ae34-06546b06caf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDY1MjQsIm5iZiI6MTczMDY0NjIyNCwicGF0aCI6Ii8xNTc3MDA1OS8zODI1NTE5ODQtZmEzOGEwOWItY2U3ZS00OTQzLWFlMzQtMDY1NDZiMDZjYWY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE1MDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwN2M5NWU2NTM5YWNlNWZiMzliODc3YTM5YTgzYjg3MGNiNDA2Yzk4MGE1MDlkMTEyNjZlMGUxNWY1OWQwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GRTOAl_zNa0ZWdyr8cvsYgEMzg1zBgz-7A54OJpBybU) [ ](https://private-user-images.githubusercontent.com/15770059/382551984-fa38a09b-ce7e-4943-ae34-06546b06caf9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDY1MjQsIm5iZiI6MTczMDY0NjIyNCwicGF0aCI6Ii8xNTc3MDA1OS8zODI1NTE5ODQtZmEzOGEwOWItY2U3ZS00OTQzLWFlMzQtMDY1NDZiMDZjYWY5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDE1MDM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwN2M5NWU2NTM5YWNlNWZiMzliODc3YTM5YTgzYjg3MGNiNDA2Yzk4MGE1MDlkMTEyNjZlMGUxNWY1OWQwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GRTOAl_zNa0ZWdyr8cvsYgEMzg1zBgz-7A54OJpBybU)

oh, the page transition thing is damn obvious for me HAHA i think cos my laptop slow, so the APIs take long time to process

**Comment by brein62** [comment]
> oh, the page transition thing is damn obvious for me HAHA i think cos my laptop slow, so the APIs take long time to process

pls show me HAHAHAH

**Review by wjayee — APPROVED** [review]
lgtm

**Review by tiongMax — COMMENTED** [review]
Can consider breaking CollaborationPage.tsx into different components as it is quite big. Overall lgtm!

**Pull request merged**
