### PR TITLE
Collaboration service frontend

### PR DESCRIPTION
**Pull request by larrywang0701**
Collaboration service frontend #83 

# Features
 - Multiple layout modes for the user to choose (in vertical splited view, you can drag the vertical bar between question area and code editor area to resize the two panels, and click the button at the middle of the vertical bar to switch the position of the two panels)
 - Code editor supporting syntax highlighting for multiple languages, supporting customizing font size and theme (light/dark) with Ace Editor

# Screenshot
image
image
image

### CODE REVIEW

**Comment by larrywang0701** [comment]
Better merge this as soon as possible, because my chatting feature #98 is depended on this PR, and #103 which will I will first work on then @brein62 will work on depends on #98.

**Comment by zacwong2151** [comment]
> Better review and merge this as soon as possible, because my chatting feature #98 (which is already WIP) is depending on this PR, and #103 which I will first work on (along with #98) then @brein62 will continue my work depends on #98.

we will merge this after the demo tonight is settled

**Review by brein62 — APPROVED** [review]
implementation-wise: LGTM! there are a few bugs but i think splitting the work and putting them in separate PRs will probably be fine here (this is a dev environment anyway)

i won't comment about the specifics of your code, but it works pretty well with our integration so far. good job!

**Comment by brein62** [comment]
**some suggestions for frontend UI/UX:**

instead of using this, use a dropdown instead

image

lack of padding between divider and question text

image

`warp` -> `wrap` in Editor Settings dropdown
image

this part is unintuitively placed at the top of the page. i think it would be better to have two buttons below the title (You are now collaborating with XXX) to allow for the change in view

image

height for the question page is too long, resulting in the End session button being put at the bottom of the page. instead, you could put the End session button below the question itself (taking inspiration from zac's current temporary frontend implementation)

image

`Vertically splited view` -> `Vertically split view`
image

**Comment by larrywang0701** [comment]
I'll merge this now to avoid conflicts with other PRs and will fix bugs in my PR about N1 chat feature.

**Comment by brein62** [comment]
ok thanks

**Pull request merged**
